pytest_failure_tracker/__init__.py,sha256=YvuYzWnKtqBb-IqG8HAu-nhIYAsgj9Vmc_b9o7vO-js,22
pytest_failure_tracker/plugin.py,sha256=v18TdVRGGTgk4gyYkh5VZPh8PgFG1mXFdHzoZT0rbz4,3103
pytest_failure_tracker-0.1.2.dist-info/LICENSE,sha256=pWiDBWmgHOAHWHO7oWN9wrGIk5uHsR62OiDffMNGDhM,1068
pytest_failure_tracker-0.1.2.dist-info/METADATA,sha256=sxJf2J_H-QK_awv8e_qn3TSGS_Ax1Uvtnb_XRaF38yg,3293
pytest_failure_tracker-0.1.2.dist-info/WHEEL,sha256=Z4pYXqR_rTB7OWNDYFOm1qRk0RX6GFP2o8LgvP453Hk,91
pytest_failure_tracker-0.1.2.dist-info/entry_points.txt,sha256=A55NgfgVi1c5EU9Ot_wElLZKkKJAGrr8XtG9LWllEUg,59
pytest_failure_tracker-0.1.2.dist-info/top_level.txt,sha256=QM3vmr7t0sH3WjTO5pbzwSwnonzZ0zDGXX7OpxMFk_k,23
pytest_failure_tracker-0.1.2.dist-info/RECORD,,
